import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Link from 'next/link'
import Layout from '../components/layout'

export default function Home() {
  return (
    <Layout>
      <div className={styles.container}>
        <Head>
          <title>Самовар</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <main className={styles.main}>
          <h3 className={styles.h3}>
            кафе
          </h3>
          <h1 className={styles.title}>
            САМОВАР
          </h1>

        </main>
      </div>
    </Layout>
  )
}
